In [ ]:
# Instalando e atualizando as bibliotecas necessárias
!pip install pyDOE
!pip install -U seaborn

In [1]:
# Importando RASD Toolbox
from RASD_TOOLBOX import *
# Importando Numpy toolbox
import numpy as n
import pandas as pd

In [2]:
w = ['NORMAL', 0.25, 0.025]
P = ['NORMAL', 10.2, 1.12]
Fy = ['NORMAL', 40.3, 4.64]

POP = [1000]

#POP = np.arange(10,1000000, 10000).tolist() # (x,y,Z); x=pop inicial; y=pop final; z=variacao pop

SETUP = {'N_REP': len(POP),
        'POP': POP,
        'N_G': 1,
        'D': 3,
        'VARS': [w, P, Fy],
        'MODEL': 'MCS'}

In [8]:
def OBJ(X):
        
    w = X[0]
    P = X[1]
    Fy = X[2]
    
    
    # STATE LIMIT FUNCTION
    
    R_0 = 80 * Fy
    S_0 = 54 * P + 5832 * w
    G_0 = S_0 - R_0

    R = [R_0] 
    S = [S_0] 
    G = [G_0]

   # p2 = P.tolist()
    #df = pd.DataFrame([P])

    #print(df[0])
    
    return R, S, G

In [9]:
RESULTS_TEST = RASD_STOCHASTIC(SETUP, OBJ)

<class 'numpy.ndarray'>
[[ 0.23303661 10.77948239 35.96583818]
 [ 0.2577319  10.64330217 43.05803402]
 [ 0.24023165  9.60499586 41.20647044]
 ...
 [ 0.26676036  9.40177429 38.94707539]
 [ 0.25059594 11.09231389 38.61949285]
 [ 0.25002235 10.03609621 35.85105031]]
<class 'numpy.ndarray'>
[ 0.23303661 10.77948239 35.96583818]
<class 'numpy.ndarray'>
[ 0.2577319  10.64330217 43.05803402]
<class 'numpy.ndarray'>
[ 0.24023165  9.60499586 41.20647044]
<class 'numpy.ndarray'>
[ 0.24366815 10.71883773 40.27754952]
<class 'numpy.ndarray'>
[ 0.25244421 12.00264689 46.06329408]
<class 'numpy.ndarray'>
[ 0.29058658 10.45777941 47.8687485 ]
<class 'numpy.ndarray'>
[ 0.1981998  11.48862127 51.5750246 ]
<class 'numpy.ndarray'>
[ 0.24350878  8.93975589 39.35593536]
<class 'numpy.ndarray'>
[ 0.27153127 11.26249792 35.35048537]
<class 'numpy.ndarray'>
[ 0.23394574 11.45324473 35.79201032]
<class 'numpy.ndarray'>
[ 0.27336341 10.98022318 43.65516959]
<class 'numpy.ndarray'>
[ 0.26277454 10.15713533 44.49

[ 0.27927835  9.15747288 35.32200775]
<class 'numpy.ndarray'>
[ 0.26078305  9.71272993 32.65777851]
<class 'numpy.ndarray'>
[ 0.28555775 12.33188973 37.72085223]
<class 'numpy.ndarray'>
[ 0.23612134 10.7449068  46.44781124]
<class 'numpy.ndarray'>
[ 0.19078218 11.71872651 43.53888899]
<class 'numpy.ndarray'>
[ 0.25670278 10.65501199 35.03867966]
<class 'numpy.ndarray'>
[ 0.28845575 10.75401907 40.30505616]
<class 'numpy.ndarray'>
[ 0.20826825 10.30986563 37.33555278]
<class 'numpy.ndarray'>
[ 0.28279171 11.88599895 42.52888672]
<class 'numpy.ndarray'>
[ 0.22462035  8.87467218 37.37536882]
<class 'numpy.ndarray'>
[ 0.30308526  9.50705547 41.67478123]
<class 'numpy.ndarray'>
[ 0.25248419  8.9174212  47.27722578]
<class 'numpy.ndarray'>
[ 0.2363609  10.26827237 45.9282292 ]
<class 'numpy.ndarray'>
[ 0.26738224 10.94793994 41.96589209]
<class 'numpy.ndarray'>
[ 0.23290713  9.40853276 46.33381539]
<class 'numpy.ndarray'>
[ 0.27624151  9.68603447 44.41674367]
<class 'numpy.ndarray'>
[ 0.2412

In [ ]:
RESULTS_TEST[len(POP)-1]['TOTAL RESULTS']

In [ ]:
DADOS = RESULTS_TEST[len(POP)-1]['TOTAL RESULTS']

In [ ]:
OPCOES_GRAFICAS = {'NAME': 'WANDER',
                'WIDTH': 0.40, 
                'HEIGHT': 0.20, 
                'X AXIS SIZE': 18,
                'Y AXIS SIZE': 18,
                'AXISES COLOR': '#000000',
                'X AXIS LABEL': ' $w$ (k/in)',
                'LABELS SIZE': 20,
                'LABELS COLOR': '#000000',  
                'CHART COLOR': '#FEB625',
                'KDE': False,
                'DPI': 600, 
                'BINS' : 18,
                'EXTENSION': '.svg'}
# RESULTS X_0 VARIABLE
OPCOES_DADOS = {'DATASET': DADOS, 'COLUMN': 'X_0'}      
# CALL PLOT
RASD_PLOT_1(OPCOES_DADOS, OPCOES_GRAFICAS)

In [ ]:
OPCOES_GRAFICAS = {'NAME': 'WANDER',
                'EXTENSION': '.svg',
                'DPI': 600,
                'WIDTH': 0.300, 
                'HEIGHT': 0.150,              
                'X DATA': 'S_0',
                'Y DATA': 'R_0',
                'X AXIS SIZE': 16,
                'Y AXIS SIZE': 16,
                'AXISES COLOR': '#000000',
                'X AXIS LABEL': '$S_0$',
                'Y AXIS LABEL': '$R_0$',
                'LABELS SIZE': 18,
                'LABELS COLOR': '#000000',
                'LOC LEGEND': 'lower right',
                'TITLE LEGEND': 'Índice de falha (I):'}
# RESULTS
OPCOES_DADOS = {'DATASET': DADOS, 'X DATA': 'S_0', 'Y DATA': 'R_0', 'HUE VALUE': 'I_0'}    
# CALL PLOT
RASD_PLOT_2(OPCOES_DADOS, OPCOES_GRAFICAS)

In [ ]:
OPCOES_GRAFICAS = {'NAME': 'WANDER',
                'EXTENSION': '.svg',
                'DPI': 600,
                'WIDTH': 0.20, 
                'HEIGHT': 0.10,              
                'X DATA': 'S_0',
                'Y DATA': 'R_0',
                'X AXIS SIZE': 16,
                'Y AXIS SIZE': 16,
                'AXISES COLOR': '#000000',
                'X AXIS LABEL': '$S_0$',
                'Y AXIS LABEL': '$R_0$',
                'LABELS SIZE': 18,
                'LABELS COLOR': '#000000',
                'G VALUE': 'G_0',
                'TRANSPARENCY': 0.8,
                'COLOR MAP': 'viridis'}


# RESULTS
OPCOES_DADOS = {'DATASET': DADOS, 'X DATA': 'S_0', 'Y DATA': 'R_0', 'G VALUE': 'G_0'}       

# CALL PLOT
RASD_PLOT_3(OPCOES_DADOS, OPCOES_GRAFICAS)

In [ ]:
OPCOES_GRAFICAS = {'NAME': 'WANDER',
                    'EXTENSION': '.svg',
                    'DPI': 600,
                    'WIDTH': 0.20,
                    'HEIGHT': 0.10,
                    'X DATA': 'S_0',
                    'Y DATA': 'R_0',
                    'X AXIS SIZE': 20,
                    'Y AXIS SIZE': 20,
                    'AXISES COLOR': '#00000',
                    'X AXIS LABEL': '$Z_0$',
                    'Y AXIS LABEL': 'Frequência',
                    'LABELS SIZE': 16,
                    'LABELS COLOR': '#000000',
                    'C VALUE': 'G_0',
                    'TRANSPARENCY': 0.8,
                    'COLOR MAP': 'viridis',
                    'BINS': '50',
                    'ALPHA': '0.5'}

# RESULTS
OPCOES_DADOS = {'DATASET': DADOS, 'X DATA': 'S_0', 'Y DATA': 'R_0', 'G VALUE': 'G_0'}       

# CALL PLOT
RASD_PLOT_4(OPCOES_DADOS, OPCOES_GRAFICAS)

In [ ]:
OPCOES_GRAFICAS = {'NAME': 'WANDER',
                    'EXTENSION': '.svg',
                    'DPI': 600,
                    'WIDTH': 0.20,
                    'HEIGHT': 0.10,
                    'X AXIS SIZE': 20,
                    'Y AXIS SIZE': 20,
                    'AXISES COLOR': '#000000',
                    'X AXIS LABEL': 'Número de Simulações (ns)',
                    'Y AXIS LABEL': 'Beta',
                    'LABELS SIZE': 16,
                    'LABELS COLOR': '#000000',
                    'CHART COLOR': 'blue',
                    'POPULATION' : POP,
                    'TYPE' : 'pf'}

# RESULTS
OPCOES_DADOS = {'DATASET': RESULTS_TEST}       

# CALL PLOT
RASD_PLOT_5(OPCOES_DADOS, OPCOES_GRAFICAS)

In [ ]:
max(POP)

In [ ]:
plt.plot( pd.Series(range(0,len(RESULTS_TEST[0]['TOTAL RESULTS']))), RESULTS_TEST[0]['TOTAL RESULTS']['I_0'], color='blue')

In [ ]:
#MESMO DATAFRAME
Bf = [ ]
Af = [ ]
c = 100
BETA_DF = pd.read_csv('RASD_TOOLBOX/beta_df.txt', delimiter = ";",  names = ['PF' ,'BETA'])

for i in POP:
   Af.append((RESULTS_TEST[len(POP)-1]['TOTAL RESULTS']['I_0'].head(i).sum())/max(POP)) # soma valores anteriores de I_0 e calcula PF

df = pd.DataFrame(Af,columns=['Pf']) #converte para DF

for i in range(len(POP)): #Salva os valores em um DF a cada 100 valores
    Bf.append((BETA_DF['PF'].sub(Af[i]).abs().idxmin())/1000)
  
plt.plot(POP, Bf, color='blue')

#plt.plot( pd.Series(range(0,len(RESULTS_TEST[0]['TOTAL RESULTS']),c)), Bf, color='blue')

#plt.plot( pd.Series(range(0,len(RESULTS_TEST[0]['TOTAL RESULTS']))), RESULTS_TEST[0]['TOTAL RESULTS']['I_0'], color='blue')

In [ ]:
plt.plot(POP, Af, color='blue')

In [ ]:
PF_AUX = []
BETA_AUX = []

for i in range (len(POP)):
    PF_AUX.append(RESULTS_TEST[i]['PROBABILITY OF FAILURE'][0])
    BETA_AUX.append(RESULTS_TEST[i]['BETA INDEX'][0])

plt.plot(POP, PF_AUX, color='blue')

In [ ]:
plt.plot(POP, BETA_AUX, color='blue')