In [ ]:
# Instalando as bibliotecas e atualizando 
!pip install pyDOE
!pip install -U seaborn
# Import MEF 1D Algorithm
!pip install -i https://test.pypi.org/simple/ FINITO-FEM-TOOLBOX


In [1]:
from FINITO_FEM_TOOLBOX import MEF1D
from RASD_TOOLBOX import RASD_STOCHASTIC
import numpy as np

In [2]:
P2Y = ['NORMAL', 15000, 2500]
P3Y = ['NORMAL', 20000, 4500]
POP = [10]

SETUP = {'N_REP': len(POP),
        'POP': POP,
        'N_G': 1,
        'D': 2,
        'VARS': [P2Y, P3Y],
        'MODEL': 'MCS'}


In [3]:
def OBJ(X):
    P2Y = X[0]
    P3Y = X[1]

    # Dataset

    FRAME_00 = {
    "TYPE_ELEMENT": 0,
    "TYPE_SOLUTION": 0,
    "N_NODES": 26,
    "N_MATERIALS": 1,
    "N_SECTIONS": 1,
    "N_ELEMENTS": 27,
    "N_DOFPRESCRIPTIONS": 6,
    "N_DOFLOADED": 24,
    "N_DOFSPRINGS": 0,
    "COORDINATES": #X,Y
    np.array([
    [0.0,0.0],
    [5.25,0.0],
    [0.0,3.0],
    [0.75,3.0],
    [1.5,3.0],
    [2.25,3.0],
    [3.0,3.0],
    [3.75,3.0],
    [4.5,3.0],
    [5.25,3.0],
    [0.0,6.0],
    [0.75,6.0],
    [1.5,6.0],
    [2.25,6.0],
    [3.0,6.0],
    [3.75,6.0],
    [4.5,6.0],
    [5.25,6.0],
    [0.0,9.0],
    [0.75,9.0],
    [1.5,9.0],
    [2.25,9.0],
    [3.0,9.0],
    [3.75,9.0],
    [4.5,9.0],
    [5.25,9.0]]),

    "ELEMENTS": #NODE 1,NODE 2,MATERIAL ID,SECTION ID,HINGE ID NODE 1,HINGE ID NODE 2
    np.array([
    [1,3,0,0,0,0],
    [2,10,0,0,0,0],
    [3,4,0,0,0,0],
    [4,5,0,0,0,0],
    [5,6,0,0,0,0],
    [6,7,0,0,0,0],
    [7,8,0,0,0,0],
    [8,9,0,0,0,0],
    [9,10,0,0,0,0],
    [3,11,0,0,0,0],
    [10,18,0,0,0,0],
    [11,12,0,0,0,0],
    [12,13,0,0,0,0],
    [13,14,0,0,0,0],
    [14,15,0,0,0,0],
    [15,16,0,0,0,0],
    [16,17,0,0,0,0],
    [17,18,0,0,0,0],
    [11,19,0,0,0,0],
    [18,26,0,0,0,0],
    [19,20,0,0,0,0],
    [20,21,0,0,0,0],
    [21,22,0,0,0,0],
    [22,23,0,0,0,0],
    [23,24,0,0,0,0],
    [24,25,0,0,0,0],
    [25,26,0,0,0,0]]),

    "MATERIALS": #YOUNG,POISSON,DENSITY,THERMAL COEFFICIENT
    np.array([
    [200E9,1,1,1E-8]]),
    "SECTIONS": #AREA,INERTIA 1,INERTIA 2,X GC,Y GC
    np.array([
    [0.0450,0.000337,0.000337,0.075,0.15]]),
    "PRESCRIBED DISPLACEMENTS": #NODE,DIRECTION(X=0,Y=1,Z=2),VALUE
    np.array([
    [0,0,0],
    [0,1,0],
    [0,2,0],
    [1,0,0],
    [1,1,0],
    [1,2,0]]),
    "ELEMENT LOADS": None,
    "NODAL LOADS":  #NODE,DIRECTION(X=0,Y=1,Z=2),VALUE
    np.array([
     [3,0,-10000,0],
    [4,0,-10000,0],
    [5,0,-10000,0],
    [6,0,-10000,0],
    [7,0,-10000,0],
    [8,0,-10000,0],
    [9,0,-10000,0],
    [10,0,-10000,0],
    [11,0,-10000,0],
    [12,0,-10000,0],
    [13,0,-10000,0],
    [14,0,-10000,0],
    [15,0,-10000,0],
    [16,0,-10000,0],
    [17,0,-10000,0],
    [18,0,-10000,0],
    [19,0,-10000,0],
    [20,0,-10000,0],
    [21,0,-10000,0],
    [22,0,-10000,0],
    [23,0,-10000,0],
    [24,0,-10000,0],
    [25,0,-10000,0],
    [26,0,-10000,0]]),
    "SPRINGS": None}


    FRAME_00_RESULTS = MEF1D(DICTIONARY = FRAME_00)
    FRAME_00_BAR_0 = FRAME_00_RESULTS[0]
    AXIAL_FORCE_LIST_BAR_0 = FRAME_00_BAR_0['N']
    N = AXIAL_FORCE_LIST_BAR_0[5]    

    S_1 = np.abs(N)
    R_1 = 143E3

    # STATE LIMIT FUNCTION

    G_0 = R_1 - S_1
    R = [R_1] 
    S = [S_1] 
    G = [G_0]

    return R, S, G

#Erro possivelmente esta no tamanho da lista elementos, fazer print de NODE_1 e NODE_2


In [4]:
RESULTS_TEST = RASD_STOCHASTIC(SETUP, OBJ)

[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]
 [12. 13. 14.]
 [15. 16. 17.]
 [18. 19. 20.]
 [21. 22. 23.]
 [24. 25. 26.]
 [27. 28. 29.]
 [30. 31. 32.]
 [33. 34. 35.]
 [36. 37. 38.]
 [39. 40. 41.]
 [42. 43. 44.]
 [45. 46. 47.]
 [48. 49. 50.]
 [51. 52. 53.]
 [54. 55. 56.]
 [57. 58. 59.]
 [60. 61. 62.]
 [63. 64. 65.]
 [66. 67. 68.]
 [69. 70. 71.]
 [72. 73. 74.]
 [75. 76. 77.]]
3
0
9
 
4
0
12
 
5
0
15
 
6
0
18
 
7
0
21
 
8
0
24
 
9
0
27
 
10
0
30
 
11
0
33
 
12
0
36
 
13
0
39
 
14
0
42
 
15
0
45
 
16
0
48
 
17
0
51
 
18
0
54
 
19
0
57
 
20
0
60
 
21
0
63
 
22
0
66
 
23
0
69
 
24
0
72
 
25
0
75
 


IndexError: index 26 is out of bounds for axis 0 with size 26

In [ ]:
RESULTS_TEST[0]['TOTAL RESULTS']

In [ ]:
FRAME_00_RESULTS = MEF1D(DICTIONARY = FRAME_00)
FRAME_00_RESULTS


In [ ]:
FRAME_00_BAR_2 = FRAME_00_RESULTS[2] 
FRAME_00_BAR_2

In [ ]:
RESULTS_TEST['TOTAL RESULTS']

In [ ]:
WANDER = RESULTS_TEST['TOTAL RESULTS']

In [ ]:
PLOT_SETUP = {'NAME': 'WANDER',
                'EXTENSION': '.svg',
                'DPI': 600,
                'WIDTH': 0.40, 
                'HEIGHT': 0.20,              
                'X DATA': 'S_0',
                'Y DATA': 'R_0',
                'X AXIS SIZE': 20,
                'Y AXIS SIZE': 20,
                'AXISES COLOR': '#000000',
                'X AXIS LABEL': '$S_0$',
                'Y AXIS LABEL': '$R_0$',
                'LABELS SIZE': 16,
                'LABELS COLOR': '#000000',
                'LOC LEGEND': 'lower right',
                'TITLE LEGEND': 'Failure index ($I$):'}
# RESULTS
DATASET =  WANDER     
# CALL PLOT
RASD_PLOT_2(DATASET, PLOT_SETUP)